name: Docker TrickyBot CI

on: [push]

jobs:
  Push:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repository
        uses: actions/checkout@v2.3.1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: trickybestia/trickybot:latest
