name: Main TrickyBot CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest

    steps:
      - name: Pull repository
        uses: actions/checkout@v2.3.1

      - name: Setup .NET 5.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: dotnet build -c Release

      - name: Create NuGet package
        shell: pwsh
        run: |
          [XML]$TargetsFile = Get-Content TrickyBot.targets
          $version = $TargetsFile.Project.PropertyGroup.Version
          $version = $Version[0].Trim()
          nuget pack -Version $version

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          - name: TrickyBot
            path: TrickyBot.Core\bin\Release
          - name: NuGet package
            path: TrickyBot.*.nupkg